<?php
namespace App\Services;

/**
 * Class AfdParser
 *
 * Responsible for reading, validating and parsing AFD (Arquivo Fonte de
 * Dados) files generated by electronic time clock devices (REP/REP-C/
 * REP-A). This parser focuses on the common layout used by most
 * equipment (portaria 1.510/2009), including layout 003, where:
 *
 *   - Registro tipo 1: Cabeçalho (informações da empresa e do
 *     equipamento)
 *   - Registro tipo 2: Alterações de dados da empresa
 *   - Registro tipo 3: Marcações de ponto
 *   - Registro tipo 4: Ajustes manuais de marcação
 *   - Registro tipo 5: Inclusão, alteração ou exclusão de empregado
 *   - Registro tipo 9: Trailer (final do arquivo)
 *
 * Each line is preserved in its original form and split into fixed
 * fields using byte offsets defined by the specification. Unknown
 * record types are stored in the "erros" array to allow manual
 * inspection. After parsing, the parser also derives a list of
 * employees and their status (ativo/excluído) based on the event
 * operations and aggregates basic statistics about the file.
 */
class AfdParser
{
    /**
     * Parse an AFD file.
     *
     * @param string $filePath Absolute path to the uploaded AFD file
     * @return array Structured representation of the AFD contents
     */
    public function parse(string $filePath): array
    {
        $handle = @fopen($filePath, 'r');
        if (!$handle) {
            throw new \RuntimeException("Não foi possível abrir o arquivo.");
        }

        $data = [
            'arquivo'          => [],
            'empresa'          => [],
            'relogio'          => [],
            'marcacoes'        => [],
            'eventosCadastro'  => [],
            'eventosEmpresa'   => [],
            'alteracoesHorario'=> [],
            'eventosOperacionais' => [],
            'linhas'           => [],
            'erros'            => [],
            'usuarios'         => []
        ];

        $lineNumber = 0;
        $firstNsr = null;
        $lastNsr = null;
        $encoding = null;

        while (($line = fgets($handle)) !== false) {
            $lineNumber++;
            // Remove quebras de linha
            $orig = rtrim($line, "\r\n");
            if ($orig === '') {
                continue;
            }

            // Detect encoding only once – assume file uses same encoding. If mbstring
            // functions are unavailable, default to UTF‑8. Some shared hostings
            // disable mbstring, which would cause undefined function errors. In
            // that case, fallback gracefully without conversion.
            if ($encoding === null) {
                if (function_exists('mb_detect_encoding')) {
                    $detected = mb_detect_encoding($orig, ['UTF-8', 'ISO-8859-1', 'Windows-1252'], true);
                    $encoding = $detected ?: 'UTF-8';
                } else {
                    $encoding = 'UTF-8';
                }
            }

            // Convert to UTF‑8 for internal processing to handle accented characters.
            // When mbstring is missing, assume the input is already UTF‑8.
            if ($encoding !== 'UTF-8') {
                if (function_exists('mb_convert_encoding')) {
                    $utf8Line = mb_convert_encoding($orig, 'UTF-8', $encoding);
                } else {
                    // Fallback: no conversion available, use original bytes
                    $utf8Line = $orig;
                }
            } else {
                $utf8Line = $orig;
            }

            // Determine NSR (first 9 digits) from the original string (length is in bytes)
            $nsr = (int) substr($orig, 0, 9);
            // Determine record type (position 10, 1 digit)
            $tipo = substr($orig, 9, 1);

            if ($firstNsr === null) {
                $firstNsr = $nsr;
            }
            $lastNsr = $nsr;

            switch ($tipo) {
                case '1':
                    // Cabeçalho do arquivo. Layout 003 (portaria 1.510) utiliza
                    // campos de tamanho fixo conforme tabela: NSR (1-9), tipo
                    // (10), tipo empregador (11), CNPJ/CPF (12‑25), CNO/CAEPF
                    // (26‑39), nome/razão social (40‑189), número de fabricação
                    // (190‑206), datas de início/fim (207‑216 e 217‑226), data e
                    // hora de geração (227‑250) em formato AAAA‑MM‑ddThh:mm:00±HHMM,
                    // versão do leiaute (251‑253), tipo e identificação do
                    // fabricante (254 e 255‑268), modelo (269‑298) e CRC (299‑302).
                    $empresa = [
                        'nsr'            => $nsr,
                        'tipoEmpregador' => substr($orig, 10, 1),
                        'cnpj_cpf'       => trim(substr($orig, 11, 14)),
                        // CNO ou CAEPF (14 posições). Pode vir vazio ou zeros.
                        'cno_caepf'      => trim(substr($orig, 25, 14)),
                        // Nome ou razão social (150 posições).
                        'nome'           => function_exists('mb_convert_encoding')
                            ? trim(mb_convert_encoding(substr($orig, 39, 150), 'UTF-8', $encoding))
                            : trim(substr($orig, 39, 150)),
                        // Número de fabricação ou processo (17 posições).
                        'serial'         => trim(substr($orig, 189, 17)),
                        // Datas de início e fim no formato AAAA‑MM‑dd.
                        'dataInicio'     => substr($orig, 206, 10),
                        'dataFim'        => substr($orig, 216, 10),
                        // Data e hora de geração no formato AAAA‑MM‑ddThh:mm:00±HHMM.
                        'dataHoraGeracao' => substr($orig, 226, 24),
                        // Versão do leiaute (3 posições, ex.: '003').
                        'layout'         => substr($orig, 250, 3),
                        // Tipo de identificação do fabricante (1 posição).
                        'tipoFabricante' => substr($orig, 253, 1),
                        // CNPJ/CPF do fabricante (14 posições).
                        'cnpjFabricante' => trim(substr($orig, 254, 14)),
                        // Modelo (30 posições).
                        'modelo'         => function_exists('mb_convert_encoding')
                            ? trim(mb_convert_encoding(substr($orig, 268, 30), 'UTF-8', $encoding))
                            : trim(substr($orig, 268, 30)),
                        // CRC do registro (4 posições, hexadecimal). Não usado no parse.
                        'crc'            => substr($orig, 298, 4),
                    ];
                    $data['empresa'] = $empresa;
                    break;

                case '2':
                    // Inclusão/alteração da identificação da empresa no REP.
                    // Layout 003 usa DH de 24 caracteres a partir da posição 11.
                    $dt = substr($orig, 10, 24);
                    $eventoEmp = [
                        'nsr'      => $nsr,
                        'datetime' => $dt,
                        'data'     => substr($dt, 0, 10),
                        'hora'     => substr($dt, 11, 5),
                        'conteudo' => $orig,
                    ];
                    $data['eventosEmpresa'][] = $eventoEmp;
                    break;

                case '3':
                    // Marcação de ponto no layout 003:
                    // NSR(9) + tipo(1) + DH(24) + PIS/CPF(12) + CRC(4)
                    $dt = substr($orig, 10, 24);
                    $marcacao = [
                        'nsr'      => $nsr,
                        'datetime' => $dt,
                        'data'     => substr($dt, 0, 10),
                        'hora'     => substr($dt, 11, 5),
                        'pis'      => trim(substr($orig, 34, 12)),
                    ];
                    $data['marcacoes'][] = $marcacao;
                    break;

                case '4':
                    // Alteração de data/hora do relógio no layout 003.
                    // NSR(9) + tipo(1) + DH anterior(24) + DH alterada(24) + CPF/PIS responsável + CRC
                    $dtAnterior = substr($orig, 10, 24);
                    $dtNovo = substr($orig, 34, 24);
                    $altHorario = [
                        'nsr'              => $nsr,
                        'datetime'         => $dtAnterior,
                        'data'             => substr($dtAnterior, 0, 10),
                        'hora'             => substr($dtAnterior, 11, 5),
                        'datetimeAnterior' => $dtAnterior,
                        'datetimeNovo'     => $dtNovo,
                        'responsavel'      => trim(substr($orig, 58, 12)),
                        'conteudo'         => $orig,
                    ];
                    $data['alteracoesHorario'][] = $altHorario;
                    break;

                case '5':
                    // Inclusão, alteração ou exclusão de empregado no layout 003:
                    // NSR(9) + tipo(1) + DH(24) + operação(1) + PIS/CPF(12) + nome(52) + demais campos.
                    $dt = substr($orig, 10, 24);
                    $operacao = substr($orig, 34, 1);
                    $pis = trim(substr($orig, 35, 12));
                    $nomeBruto = substr($orig, 47, 52);
                    $nome = function_exists('mb_convert_encoding')
                        ? trim(mb_convert_encoding($nomeBruto, 'UTF-8', $encoding))
                        : trim($nomeBruto);
                    $eventoCad = [
                        'nsr'      => $nsr,
                        'datetime' => $dt,
                        'data'     => substr($dt, 0, 10),
                        'hora'     => substr($dt, 11, 5),
                        'operacao' => $operacao,
                        'pis'      => $pis,
                        'nome'     => $nome,
                    ];
                    $data['eventosCadastro'][] = $eventoCad;
                    break;

                case '6':
                    // Registro operacional do equipamento.
                    $dt = substr($orig, 10, 24);
                    $data['eventosOperacionais'][] = [
                        'nsr'      => $nsr,
                        'datetime' => $dt,
                        'data'     => substr($dt, 0, 10),
                        'hora'     => substr($dt, 11, 5),
                        'conteudo' => $orig,
                    ];
                    break;

                case '9':
                    // Trailer (final do arquivo)
                    // Geralmente contém apenas o NSR e tipo, mas alguns fabricantes
                    // adicionam mais campos. Guardamos o registro bruto.
                    $data['arquivo']['trailer'] = [
                        'nsr'   => $nsr,
                        'conteudo' => $orig,
                    ];
                    break;

                default:
                    // Registro não reconhecido
                    $data['erros'][] = [
                        'linha'    => $lineNumber,
                        'nsr'      => $nsr,
                        'tipo'     => $tipo,
                        'conteudo' => $orig,
                    ];
                    break;
            }

            // Registrar linha genérica para listagem "Linha a linha"
            $data['linhas'][] = [
                'linha'    => $lineNumber,
                'nsr'      => $nsr,
                'tipo'     => $tipo,
                'conteudo' => $orig,
            ];
        }
        fclose($handle);

        // Preencher algumas estatísticas do arquivo.
        // Para o resumo, considera-se como primeiro/último NSR útil registros
        // de marcação ou cadastro (tipos 3 e 5), pois os primeiros registros do
        // arquivo podem ser operacionais ou alterações de empresa.
        $registrosUteis = array_merge($data['eventosCadastro'], $data['marcacoes']);
        usort($registrosUteis, static function ($a, $b) {
            return ($a['nsr'] ?? 0) <=> ($b['nsr'] ?? 0);
        });
        $primeiroUtil = $registrosUteis[0] ?? null;
        $ultimoUtil = $registrosUteis ? $registrosUteis[count($registrosUteis) - 1] : null;

        $data['arquivo']['primeiroNsr'] = $primeiroUtil['nsr'] ?? $firstNsr;
        $data['arquivo']['ultimoNsr']   = $ultimoUtil['nsr'] ?? $lastNsr;
        $data['arquivo']['dataPrimeiroNsr'] = $primeiroUtil['data'] ?? null;
        $data['arquivo']['dataUltimoNsr']   = $ultimoUtil['data'] ?? null;
        $data['arquivo']['numeroLinhas'] = count($data['linhas']);

        // Derivar usuários a partir dos eventos de cadastro e marcações
        $usuarios = [];
        foreach ($data['eventosCadastro'] as $cad) {
            $pis = $cad['pis'];
            if (!isset($usuarios[$pis])) {
                $usuarios[$pis] = [
                    'pis'        => $pis,
                    'nome'       => $cad['nome'] ?: '',
                    'eventos'    => [],
                    'marcacoes'  => [],
                    'ativo'      => true,
                ];
            }
            $usuarios[$pis]['eventos'][] = $cad;
            // Operações: I (inclusão), A (alteração), E (exclusão)
            if ($cad['operacao'] === 'E') {
                $usuarios[$pis]['ativo'] = false;
            } elseif ($cad['operacao'] === 'I') {
                $usuarios[$pis]['ativo'] = true;
            }
            if ($cad['nome'] !== '') {
                $usuarios[$pis]['nome'] = $cad['nome'];
            }
        }
        foreach ($data['marcacoes'] as $marc) {
            $pis = $marc['pis'];
            if (!isset($usuarios[$pis])) {
                $usuarios[$pis] = [
                    'pis'        => $pis,
                    'nome'       => '',
                    'eventos'    => [],
                    'marcacoes'  => [],
                    'ativo'      => true,
                ];
            }
            $usuarios[$pis]['marcacoes'][] = $marc;
        }
        $data['usuarios'] = $usuarios;

        return $data;
    }
}